---
- name: Loop Demo
  hosts: all

  vars:
    package_list:
      - mc
      - ansible
      - htop

  tasks:
  - name: Install latest packages
    apt:
      name: "{{package_list}}"
      state: latest
  
  - name: Install latest packages (Loop)
    apt:
      name: "{{item}}"
      state: latest
    loop: "{{package_list}}"
     
  - name: Install latest packages (With)
    apt:
      name: "{{item.name}}"
      state: "{{item.state}}"
    with_items:
      - {name: mc, state: latest}
      - {name: ansible, state: latest}
      - {name: htop, state: latest}
