---
- name: Loops & Conditions Demo
  hosts: all

  vars:
    package_list:
      - mc
      - ansible
      - htop

  tasks:

#Conditions

  - name: Conditional task (Debian)
    apt:
      name: "{{package_list}}"
      state: latest
    when: ansible_os_family == "Debian"

  - name: Conditional task (RedHat)
    yum:
      name: "{{package_list}}"
      state: latest
    when: ansible_os_family == "RedHat"
    
#Block

  - name: Block Tasks
    block:
      - name: Install latest packages (Block)
        apt:
          name: "{{package_list}}"
          state: latest

      - name: Install latest packages (Block Loop)
        apt:
          name: "{{item}}"
          state: latest
        loop: "{{package_list}}"
    when: ansible_os_family == "Debian"