---
- name: Copy config
  hosts: all
  remote_user: ubuntu

  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: ./hosts.yaml
      dest: ~/hosts.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

- name: Ping
  hosts: all
  remote_user: ubuntu
  tasks:
    - name: Ping
      ping: